### ISSUE TITLE
Failed to launch browser! No usable sandbox!

### ISSUE THREAD

**Issue by Tahlor** [fpnewton/DailyWirePodcastProxy#34]
I'm getting a browser error using the `ghcr.io/fpnewton/dailywirepodcastproxy:master` container on Ubuntu 22. What am I missing?

```
sudo docker run -it -p 9473:9473 -v ./DailyWirePodcastProxy.ini:/opt/publish/linux-x64/DailyWirePodcastProxy.ini --name dailywire-podcast-proxy --entrypoint /bin/bash ghcr.io/fpnewton/dailywirepodcastproxy:master
dwpp@97bbf25ffd50:/opt/publish/linux-x64$
dwpp@97bbf25ffd50:/opt/publish/linux-x64$ cd /opt/publish/linux-x64
./DailyWirePodcastProxy
info: DailyWireAuthentication.Services.TokenService[0]
      No access token was found in token store
Unhandled exception. System.InvalidOperationException: The configuration is invalid. Creating the instance for type ListPodcastEpisodeQueryHandler failed. Failed to resolve IGraphQLClient. IGraphQLClient is a cross-wired service, meaning that Simple Injector forwarded the request the framework's IServiceProvider in order to get an instance. The used Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, however, failed with the following message: "One or more errors occurred. (Failed to launch browser! [0715/163752.042027:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c05c0d50 logging::LogMessage::~LogMessage()
#3 0x58f1be6815db content::ZygoteHostImpl::Init()
#4 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x58f1c0158eb9 content::RunContentProcess()
#6 0x58f1c015900e content::ContentMain()
#7 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#8 0x58f1c01b3cd5 headless::HeadlessShellMain()
#9 0x58f1bcda5668 ChromeMain
#10 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#11 0x7b087391de40 __libc_start_main
#12 0x58f1bcda54aa _start

Received signal 6
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c0646f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7b0873936520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x7b087398aa7c pthread_kill
#5 0x7b0873936476 raise
#6 0x7b087391c7f3 abort
#7 0x58f1c06461f5 base::debug::BreakDebuggerAsyncSafe()
#8 0x58f1c05c1221 logging::LogMessage::~LogMessage()
#9 0x58f1be6815db content::ZygoteHostImpl::Init()
#10 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#11 0x58f1c0158eb9 content::RunContentProcess()
#12 0x58f1c015900e content::ContentMain()
#13 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#14 0x58f1c01b3cd5 headless::HeadlessShellMain()
#15 0x58f1bcda5668 ChromeMain
#16 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#17 0x7b087391de40 __libc_start_main
#18 0x58f1bcda54aa _start
  r8: 00007ffe4235cce0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000006 r13: 0000000000000016 r14: 00007ffe4235deb0 r15: 0000369800238800
  di: 0000000000000038  si: 0000000000000038  bp: 0000000000000038  bx: 00007b087280b2c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007b087398aa7c  sp: 00007ffe4235cc10
  ip: 00007b087398aa7c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
)". This error might indicate a misconfiguration of services in the framework's IServiceCollection.
 ---> SimpleInjector.ActivationException: Failed to resolve IGraphQLClient. IGraphQLClient is a cross-wired service, meaning that Simple Injector forwarded the request the framework's IServiceProvider in order to get an instance. The used Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, however, failed with the following message: "One or more errors occurred. (Failed to launch browser! [0715/163752.042027:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c05c0d50 logging::LogMessage::~LogMessage()
#3 0x58f1be6815db content::ZygoteHostImpl::Init()
#4 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x58f1c0158eb9 content::RunContentProcess()
#6 0x58f1c015900e content::ContentMain()
#7 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#8 0x58f1c01b3cd5 headless::HeadlessShellMain()
#9 0x58f1bcda5668 ChromeMain
#10 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#11 0x7b087391de40 __libc_start_main
#12 0x58f1bcda54aa _start

Received signal 6
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c0646f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7b0873936520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x7b087398aa7c pthread_kill
#5 0x7b0873936476 raise
#6 0x7b087391c7f3 abort
#7 0x58f1c06461f5 base::debug::BreakDebuggerAsyncSafe()
#8 0x58f1c05c1221 logging::LogMessage::~LogMessage()
#9 0x58f1be6815db content::ZygoteHostImpl::Init()
#10 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#11 0x58f1c0158eb9 content::RunContentProcess()
#12 0x58f1c015900e content::ContentMain()
#13 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#14 0x58f1c01b3cd5 headless::HeadlessShellMain()
#15 0x58f1bcda5668 ChromeMain
#16 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#17 0x7b087391de40 __libc_start_main
#18 0x58f1bcda54aa _start
  r8: 00007ffe4235cce0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000006 r13: 0000000000000016 r14: 00007ffe4235deb0 r15: 0000369800238800
  di: 0000000000000038  si: 0000000000000038  bp: 0000000000000038  bx: 00007b087280b2c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007b087398aa7c  sp: 00007ffe4235cc10
  ip: 00007b087398aa7c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
)". This error might indicate a misconfiguration of services in the framework's IServiceCollection.
 ---> System.InvalidOperationException: Failed to resolve IGraphQLClient. IGraphQLClient is a cross-wired service, meaning that Simple Injector forwarded the request the framework's IServiceProvider in order to get an instance. The used Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, however, failed with the following message: "One or more errors occurred. (Failed to launch browser! [0715/163752.042027:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c05c0d50 logging::LogMessage::~LogMessage()
#3 0x58f1be6815db content::ZygoteHostImpl::Init()
#4 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x58f1c0158eb9 content::RunContentProcess()
#6 0x58f1c015900e content::ContentMain()
#7 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#8 0x58f1c01b3cd5 headless::HeadlessShellMain()
#9 0x58f1bcda5668 ChromeMain
#10 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#11 0x7b087391de40 __libc_start_main
#12 0x58f1bcda54aa _start

Received signal 6
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c0646f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7b0873936520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x7b087398aa7c pthread_kill
#5 0x7b0873936476 raise
#6 0x7b087391c7f3 abort
#7 0x58f1c06461f5 base::debug::BreakDebuggerAsyncSafe()
#8 0x58f1c05c1221 logging::LogMessage::~LogMessage()
#9 0x58f1be6815db content::ZygoteHostImpl::Init()
#10 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#11 0x58f1c0158eb9 content::RunContentProcess()
#12 0x58f1c015900e content::ContentMain()
#13 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#14 0x58f1c01b3cd5 headless::HeadlessShellMain()
#15 0x58f1bcda5668 ChromeMain
#16 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#17 0x7b087391de40 __libc_start_main
#18 0x58f1bcda54aa _start
  r8: 00007ffe4235cce0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000006 r13: 0000000000000016 r14: 00007ffe4235deb0 r15: 0000369800238800
  di: 0000000000000038  si: 0000000000000038  bp: 0000000000000038  bx: 00007b087280b2c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007b087398aa7c  sp: 00007ffe4235cc10
  ip: 00007b087398aa7c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
)". This error might indicate a misconfiguration of services in the framework's IServiceCollection.
 ---> System.AggregateException: One or more errors occurred. (Failed to launch browser! [0715/163752.042027:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c05c0d50 logging::LogMessage::~LogMessage()
#3 0x58f1be6815db content::ZygoteHostImpl::Init()
#4 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x58f1c0158eb9 content::RunContentProcess()
#6 0x58f1c015900e content::ContentMain()
#7 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#8 0x58f1c01b3cd5 headless::HeadlessShellMain()
#9 0x58f1bcda5668 ChromeMain
#10 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#11 0x7b087391de40 __libc_start_main
#12 0x58f1bcda54aa _start

Received signal 6
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c0646f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7b0873936520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x7b087398aa7c pthread_kill
#5 0x7b0873936476 raise
#6 0x7b087391c7f3 abort
#7 0x58f1c06461f5 base::debug::BreakDebuggerAsyncSafe()
#8 0x58f1c05c1221 logging::LogMessage::~LogMessage()
#9 0x58f1be6815db content::ZygoteHostImpl::Init()
#10 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#11 0x58f1c0158eb9 content::RunContentProcess()
#12 0x58f1c015900e content::ContentMain()
#13 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#14 0x58f1c01b3cd5 headless::HeadlessShellMain()
#15 0x58f1bcda5668 ChromeMain
#16 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#17 0x7b087391de40 __libc_start_main
#18 0x58f1bcda54aa _start
  r8: 00007ffe4235cce0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000006 r13: 0000000000000016 r14: 00007ffe4235deb0 r15: 0000369800238800
  di: 0000000000000038  si: 0000000000000038  bp: 0000000000000038  bx: 00007b087280b2c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007b087398aa7c  sp: 00007ffe4235cc10
  ip: 00007b087398aa7c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
)
 ---> PuppeteerSharp.ProcessException: Failed to launch browser! [0715/163752.042027:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c05c0d50 logging::LogMessage::~LogMessage()
#3 0x58f1be6815db content::ZygoteHostImpl::Init()
#4 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#5 0x58f1c0158eb9 content::RunContentProcess()
#6 0x58f1c015900e content::ContentMain()
#7 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#8 0x58f1c01b3cd5 headless::HeadlessShellMain()
#9 0x58f1bcda5668 ChromeMain
#10 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#11 0x7b087391de40 __libc_start_main
#12 0x58f1bcda54aa _start

Received signal 6
#0 0x58f1c0647469 base::debug::CollectStackTrace()
#1 0x58f1c05adf33 base::debug::StackTrace::StackTrace()
#2 0x58f1c0646f71 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7b0873936520 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x4251f)
#4 0x7b087398aa7c pthread_kill
#5 0x7b0873936476 raise
#6 0x7b087391c7f3 abort
#7 0x58f1c06461f5 base::debug::BreakDebuggerAsyncSafe()
#8 0x58f1c05c1221 logging::LogMessage::~LogMessage()
#9 0x58f1be6815db content::ZygoteHostImpl::Init()
#10 0x58f1c015adf2 content::ContentMainRunnerImpl::Initialize()
#11 0x58f1c0158eb9 content::RunContentProcess()
#12 0x58f1c015900e content::ContentMain()
#13 0x58f1c01b3fca headless::(anonymous namespace)::RunContentMain()
#14 0x58f1c01b3cd5 headless::HeadlessShellMain()
#15 0x58f1bcda5668 ChromeMain
#16 0x7b087391dd90 (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
#17 0x7b087391de40 __libc_start_main
#18 0x58f1bcda54aa _start
  r8: 00007ffe4235cce0  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000006 r13: 0000000000000016 r14: 00007ffe4235deb0 r15: 0000369800238800
  di: 0000000000000038  si: 0000000000000038  bp: 0000000000000038  bx: 00007b087280b2c0
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007b087398aa7c  sp: 00007ffe4235cc10
  ip: 00007b087398aa7c efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]

   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 83
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 89
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 61
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 84
   at DailyWireAuthentication.Handlers.PasswordLoginHandler.GetAuthorizationCode() in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWireAuthentication/Handlers/PasswordLoginHandler.cs:line 62
   at DailyWireAuthentication.Handlers.PasswordLoginHandler.LoginPasswordAsync(CancellationToken cancellationToken) in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWireAuthentication/Handlers/PasswordLoginHandler.cs:line 33
   at DailyWireAuthentication.Services.TokenService.GetAccessToken(CancellationToken cancellationToken) in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWireAuthentication/Services/TokenService.cs:line 57
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DailyWirePodcastProxy.Configuration.GraphQLConfiguration.<>c__DisplayClass0_0.<AddGraphQLClient>b__1(IServiceProvider serviceProvider) in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWirePodcastProxy/Configuration/GraphQLConfiguration.cs:line 27
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   --- End of inner exception stack trace ---
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at SimpleInjector.SimpleInjectorServiceCollectionExtensions.<>c__DisplayClass19_0.<BuildScopedInstanceCreator>b__0()
   at lambda_method27(Closure )
   at lambda_method28(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstanceInternal(ScopedRegistration registration, Dictionary`2 cache)
   at SimpleInjector.Scope.GetInstanceInternal(ScopedRegistration registration)
   at lambda_method29(Closure )
   at SimpleInjector.Scope.CreateAndCacheInstanceInternal(ScopedRegistration registration, Dictionary`2 cache)
   at SimpleInjector.Scope.GetInstanceInternal(ScopedRegistration registration)
   at lambda_method60(Closure )
   at SimpleInjector.InstanceProducer.BuildAndReplaceInstanceCreatorAndCreateFirstInstance()
   at SimpleInjector.InstanceProducer.GetInstance()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.GetInstance()
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   --- End of inner exception stack trace ---
   at SimpleInjector.InstanceProducer.VerifyInstanceCreation()
   at SimpleInjector.Container.VerifyInstanceCreation(InstanceProducer[] producersToVerify, Scope verificationScope)
   at SimpleInjector.Container.VerifyThatAllRootObjectsCanBeCreated(Scope verificationScope)
   at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
   at SimpleInjector.Container.Verify(VerificationOption option)
   at SimpleInjector.Container.Verify()
   at DailyWirePodcastProxy.Configuration.SimpleInjectorConfiguration.EnableSimpleInjector(WebApplication app) in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWirePodcastProxy/Configuration/SimpleInjectorConfiguration.cs:line 40
   at Program.<Main>$(String[] args) in /home/runner/work/DailyWirePodcastProxy/DailyWirePodcastProxy/src/DailyWirePodcastProxy/Program.cs:line 30
   at Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by fpnewton** [comment]
New release is now available to address this issue.
